[graph]
all-features = true

[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
  "https://github.com/rust-lang/crates.io-index",
  "sparse+https://index.crates.io/",
]
allow-git = []
